apiVersion: v1
kind: Service
metadata:
  name: pulsebackend-service
  namespace: dev

spec:
  selector:
    app: pulsebackend-development
  ports:
    - port: 8080 # Port exposed by the service
      targetPort: 8080  # Port app is listening on in the pod

# Running on localhost:  kubectl port-forward -n dev service/pulsebackend-service 8080:8080