name: "Build, Test and Deploy"
run-name: ${{ github.actor }} is testing out continuous integration in GitHub Actions

on:
  push:
    branches:
      - "*" # Simply run this workflow on every push
    paths:
      - "pulsebackend/**" # Run when files change in the backend folder only
      - ".github/workflows/backend-ci.yml" # Run when content of backend-ci changes

jobs:
  tests:
    name: "CI Tests"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code to run on GITHUB_WORKSPACE"
        uses: actions/checkout@v4

      - name: "Setup JDK 17"
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          cache: "maven"

      - name: "Run unit tests"
        run: mvn --batch-mode test --file pulsebackend/pom.xml

      - name: "Run integration tests"
        run: mvn --batch-mode verify --file pulsebackend/pom.xml -Pintegration-tests # run integration tests with profile integration-test defined in pom.xml

  build:
    name: "Build application image"
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code to run on GITHUB_WORKSPACE"
        uses: actions/checkout@v4

      # TODO: Maybe find a way to de-duplicate this step
      - name: "Setup JDK 17"
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          cache: "maven"

      - name: "Build application Jar"
        run: |
          mvn --batch-mode clean package -DskipTests --file pulsebackend/pom.xml
          ls pulsebackend/target

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: "Build pulsebackend Docker image"
        uses: docker/build-push-action@v6
        with:
          context: . # Keep the context root because Dockerfile handles where the jar is at
          push: false # false = just build the image for now
          load: true # load the image in the docker daemon
          file: ./pulsebackend/src/main/docker/Dockerfile
          tags: |
            pulsebackend:latest
            pulsebackend:${{ github.sha }}

      - name: "Verify Docker Image Build"
        run: docker image ls | grep pulsebackend
