name: "Build, Test and Deploy"
run-name: ${{ github.actor }} is testing out continuous integration in GitHub Actions

on:
  push:
    branches:
      - "*" # Simply run this workflow on every push
    paths:
      - "pulsebackend/**" # Run when files change in the backend folder only
      - ".github/workflows/backend-ci.yml" # Run when content of backend-ci changes

jobs:
  tests:
    name: "CI Tests"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code to run on GITHUB_WORKSPACE"
        uses: actions/checkout@v4

      - name: "Setup JDK 17"
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          cache: "maven"

      - name: "Run unit tests"
        run: mvn --batch-mode test --file pulsebackend/pom.xml

      - name: "Run integration tests"
        run: mvn --batch-mode verify --file pulsebackend/pom.xml -Pintegration-tests # run integration tests with profile integration-test defined in pom.xml

  build:
    name: "Build application image"
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code to run on GITHUB_WORKSPACE"
        uses: actions/checkout@v4

      # TODO: Maybe find a way to de-duplicate this step
      - name: "Setup JDK 17"
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          cache: "maven"

      - name: "Build application Jar"
        run: |
          mvn --batch-mode clean package -DskipTests --file pulsebackend/pom.xml
          ls pulsebackend/target

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Extract metadata for Docker"
        id: meta # for later use in the below workflows
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/pulsebackend
          tags: |
            type=sha,format=short
            type=ref,event=branch
            latest

      - name: "Build and Push Docker image to GitHub Container Registry"
        uses: docker/build-push-action@v6
        with:
          context: . # Keep the context root because Dockerfile handles where the jar is at
          push: true # false = just build the image for now
          file: ./pulsebackend/src/main/docker/Dockerfile
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/${{ github.repository }}/pulsebackend:sha-${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
